import Head from "next/head";
import Hero from "components/Hero/Hero";
import Companies from "components/Companies/Companies";
import { useRef } from "react";
import Search from "components/Search/Search";

export default function Home() {
  const companiesRef = useRef(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8 flex flex-col">
        <div className="h-screen flex justify-center items-center">
          <Hero
            onScrollClick={() => {
              window.scrollTo({
                top: 800,
                behavior: "smooth",
              });
            }}
          />
        </div>
        <div ref={companiesRef}>
          <Companies />
        </div>
      </main>
    </>
  );
}
