import Head from "next/head";
import companies from "../../data/data.json";
import Image from "next/image";
import Hero from "components/Hero/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        {/* <h1>Top Tech Startups Hiring 2023</h1> */}
        <Hero />
        {/* {companies.map((item, index) => {
          return (
            <div key={index}>
              <h1>{item.company_name}</h1>
              <p>{item.headline}</p>
              <Image
                src={`/images/images/${item.id}.jpg`}
                alt="MF Logo"
                width={100}
                height={100}
              />
            </div>
          );
        })} */}
      </main>
    </>
  );
}
