import Head from "next/head";
import Hero from "components/Hero/Hero";
import { useRef } from "react";
import axios from "axios";
import MyCard from "../../components/Card/Card";
import Link from "next/link";

export default function Home({ data }) {
  const companiesRef = useRef(null);

  return (
    <>
      <Head>
        <title>Tech Startups</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8 flex flex-col">
        <div className="h-screen flex justify-center items-center">
          <Hero
            onScrollClick={() => {
              window.scrollTo({
                top: 800,
                behavior: "smooth",
              });
            }}
          />
        </div>
        <div ref={companiesRef}>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {data.map((item, index) => {
              return (
                <Link key={index} href={`/companies/${index}`}>
                  <MyCard
                    src={`/images/images/${item.id}.jpg`}
                    title={item.company_name}
                    description={item.headline}
                    avatarSrc={`/images/images/${item.id}.jpg`}
                  />
                </Link>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/companies");
  const data = await res.data;
  return {
    props: {
      data,
    },
  };
};
